// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@financetracker.local"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/accounts": {
            "get": {
                "description": "Get all user accounts with converted amounts to main currency",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "List all accounts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ListAccountsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new financial account with specified currency and amount",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Create a new account",
                "parameters": [
                    {
                        "description": "Account data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.AccountResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/accounts/{id}": {
            "get": {
                "description": "Get a single account with converted amounts",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Get account by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AccountResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update account details (name, type, amount, description)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Update account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AccountResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an account permanently",
                "tags": [
                    "accounts"
                ],
                "summary": "Delete account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/currencies": {
            "get": {
                "description": "Get detailed list of all currencies including provider preferences",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List all currencies (admin)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.CurrencyInfoResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Add a new currency to the system with provider preferences",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Create new currency",
                "parameters": [
                    {
                        "description": "Currency data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateCurrencyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CurrencyInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/currencies/{code}": {
            "get": {
                "description": "Get detailed information about a specific currency",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get currency details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Currency code (e.g., BTC, USD)",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CurrencyInfoResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update currency properties (name, precision, symbol, etc.)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Update currency",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Currency code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateCurrencyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CurrencyInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Soft delete a currency (mark as inactive)",
                "tags": [
                    "admin"
                ],
                "summary": "Delete currency",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Currency code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/currencies/{code}/providers": {
            "put": {
                "description": "Set primary and fallback providers for a currency",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Update currency provider preferences",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Currency code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Provider preferences",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateProvidersRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CurrencyInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/currencies": {
            "get": {
                "description": "Get all supported currencies with their properties",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "currencies"
                ],
                "summary": "List all currencies",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ListCurrenciesResponse"
                        }
                    }
                }
            }
        },
        "/portfolio": {
            "get": {
                "description": "Get real-time total balance and breakdown across all accounts",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "portfolio"
                ],
                "summary": "Get current portfolio statistics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target currency for conversion (default: user's main currency)",
                        "name": "currency",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.StatisticsResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/portfolio/history": {
            "get": {
                "description": "Get daily portfolio snapshots for a date range",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "portfolio"
                ],
                "summary": "Get portfolio history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD, default: 30 days ago)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD, default: today)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{from: string, to: string, count: int, data: []PortfolioSnapshot}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/portfolio/trend": {
            "get": {
                "description": "Calculate growth metrics over a time period",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "portfolio"
                ],
                "summary": "Get portfolio trend",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Time period: 7d, 30d, 90d, 1y (default: 30d)",
                        "name": "period",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.PortfolioTrend"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rates/refresh": {
            "post": {
                "description": "Trigger immediate fetch of exchange rates from all providers",
                "tags": [
                    "rates"
                ],
                "summary": "Refresh exchange rates",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/settings": {
            "get": {
                "description": "Get current user settings including main currency preference",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Get user settings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Settings"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update all user settings (full replacement)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Update user settings",
                "parameters": [
                    {
                        "description": "Settings data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateSettingsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Settings"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/snapshots": {
            "get": {
                "description": "Get portfolio snapshots for a date range",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "snapshots"
                ],
                "summary": "List portfolio snapshots",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD, default: 30 days ago)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD, default: today)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{from: string, to: string, count: int, data: []PortfolioSnapshot}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a manual portfolio snapshot for a specific date",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "snapshots"
                ],
                "summary": "Create portfolio snapshot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Date to create snapshot for (YYYY-MM-DD, default: today)",
                        "name": "date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.PortfolioSnapshot"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/snapshots/{date}": {
            "get": {
                "description": "Get detailed portfolio state for a specific date",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "snapshots"
                ],
                "summary": "Get snapshot by date",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Date (YYYY-MM-DD)",
                        "name": "date",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.PortfolioSnapshot"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.CurrencyType": {
            "type": "string",
            "enum": [
                "fiat",
                "crypto",
                "metal",
                "commodity",
                "stock"
            ],
            "x-enum-comments": {
                "CurrencyTypeCommodity": "Reserved for future",
                "CurrencyTypeCrypto": "BTC, ETH",
                "CurrencyTypeFiat": "USD, EUR, RUB, CNY",
                "CurrencyTypeMetal": "GOLD, SILVER",
                "CurrencyTypeStock": "Reserved for future"
            },
            "x-enum-descriptions": [
                "USD, EUR, RUB, CNY",
                "BTC, ETH",
                "GOLD, SILVER",
                "Reserved for future",
                "Reserved for future"
            ],
            "x-enum-varnames": [
                "CurrencyTypeFiat",
                "CurrencyTypeCrypto",
                "CurrencyTypeMetal",
                "CurrencyTypeCommodity",
                "CurrencyTypeStock"
            ]
        },
        "domain.PortfolioSnapshot": {
            "type": "object",
            "properties": {
                "account_count": {
                    "type": "integer"
                },
                "accounts": {
                    "description": "Joined data",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.PortfolioSnapshotAccount"
                    }
                },
                "calculation_duration_ms": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "integer"
                },
                "currency_count": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "snapshot_date": {
                    "description": "YYYY-MM-DD",
                    "type": "string"
                },
                "snapshot_timestamp": {
                    "type": "integer"
                },
                "total_balance_float": {
                    "type": "number"
                },
                "total_balance_usd": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "domain.PortfolioSnapshotAccount": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "account_name": {
                    "type": "string"
                },
                "account_type": {
                    "type": "string"
                },
                "amount": {
                    "type": "integer"
                },
                "amount_float": {
                    "type": "number"
                },
                "converted_amount_float": {
                    "type": "number"
                },
                "converted_amount_usd": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "integer"
                },
                "currency_code": {
                    "type": "string"
                },
                "currency_precision": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "rate_source": {
                    "type": "string"
                },
                "rate_timestamp": {
                    "type": "integer"
                },
                "rate_to_usd": {
                    "type": "number"
                },
                "snapshot_id": {
                    "type": "string"
                }
            }
        },
        "domain.PortfolioTrend": {
            "type": "object",
            "properties": {
                "change_amount": {
                    "type": "number"
                },
                "change_percent": {
                    "type": "number"
                },
                "daily_growth_rate": {
                    "description": "CAGR for the period",
                    "type": "number"
                },
                "end_balance": {
                    "type": "number"
                },
                "period": {
                    "description": "\"7d\", \"30d\", \"1y\"",
                    "type": "string"
                },
                "start_balance": {
                    "type": "number"
                }
            }
        },
        "domain.ProviderPreference": {
            "type": "object",
            "properties": {
                "priority": {
                    "description": "1 = primary, 2 = fallback 1, etc.",
                    "type": "integer"
                },
                "provider": {
                    "description": "e.g., \"coingecko\"",
                    "type": "string"
                }
            }
        },
        "domain.Settings": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "main_currency": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.AccountResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "converted_amount": {
                    "type": "integer"
                },
                "converted_float": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "exchange_rate": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "main_currency": {
                    "description": "Conversion to user's main currency",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "precision": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.CreateAccountRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "currency": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dto.CreateCurrencyRequest": {
            "type": "object",
            "properties": {
                "base_unit": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "precision": {
                    "type": "integer"
                },
                "provider_prefs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ProviderPreference"
                    }
                },
                "symbol": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/domain.CurrencyType"
                }
            }
        },
        "dto.CurrencyInfoResponse": {
            "type": "object",
            "properties": {
                "base_unit": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "fallback_providers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "precision": {
                    "type": "integer"
                },
                "primary_provider": {
                    "description": "Computed",
                    "type": "string"
                },
                "provider_prefs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ProviderPreference"
                    }
                },
                "symbol": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/domain.CurrencyType"
                },
                "updated_at": {
                    "type": "integer"
                }
            }
        },
        "dto.CurrencyResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "precision": {
                    "type": "integer"
                }
            }
        },
        "dto.ListAccountsResponse": {
            "type": "object",
            "properties": {
                "accounts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AccountResponse"
                    }
                }
            }
        },
        "dto.ListCurrenciesResponse": {
            "type": "object",
            "properties": {
                "currencies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CurrencyResponse"
                    }
                }
            }
        },
        "dto.UpdateAccountRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateCurrencyRequest": {
            "type": "object",
            "properties": {
                "base_unit": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "precision": {
                    "type": "integer"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateProvidersRequest": {
            "type": "object",
            "properties": {
                "providers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ProviderPreference"
                    }
                }
            }
        },
        "dto.UpdateSettingsRequest": {
            "type": "object",
            "properties": {
                "main_currency": {
                    "type": "string"
                }
            }
        },
        "service.RateInfo": {
            "type": "object",
            "properties": {
                "from_currency": {
                    "type": "string"
                },
                "rate": {
                    "type": "number"
                },
                "source": {
                    "type": "string"
                },
                "to_currency": {
                    "type": "string"
                }
            }
        },
        "service.StatisticsResult": {
            "type": "object",
            "properties": {
                "accounts": {
                    "type": "integer"
                },
                "rates_used": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.RateInfo"
                    }
                },
                "target_currency": {
                    "type": "string"
                },
                "total_amount": {
                    "description": "In smallest units",
                    "type": "integer"
                },
                "total_float": {
                    "description": "Human-readable",
                    "type": "number"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Finance Tracker API",
	Description:      "Personal finance tracking API with multi-currency support",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
